[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake"]

[phases.install]
cmds = ["cd backend && rm -rf node_modules package-lock.json && npm install"]

[start]
cmd = "cd backend && node server.js"

